apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: searxng
  namespace: searxng
spec:
  defaultBackend:
    service:
      name: searxng
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
        - searxng
