---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: jellyfin
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: jellyfin
  policy:
    semver:
      range: '>=10.10.7 <10.11.0'
