---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: lidarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: lidarr
  policy:
    semver:
      range: '>=3.0.0 <4.0.0'