---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: prowlarr
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: prowlarr
  policy:
    semver:
      range: '>=1.0.0 <2.0.0'
