---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: media
spec:
  capacity:
    storage: 4Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
  nfs:
    readOnly: false
    path: /Media
    server: 10.240.1.43
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media
  namespace: saga
spec:
  volumeName: media
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Ti