---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config
  namespace: qbittorrent
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-trusty
  resources:
    requests:
      storage: 100Mi
