---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    lun: 0
    iqn: iqn.2004-04.com.qnap:ts-233:iscsi.homelab.7069f3
    targetPortal: 10.240.1.43
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin
  namespace: saga
spec:
  resources:
    requests:
      storage: 10Gi
  volumeName: jellyfin
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: saga
spec:
  storageClassName: longhorn-trusty
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce