---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: saga
spec:
  storageClassName: longhorn-trusty
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
