---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
spec:
  selector:
    matchLabels:
      app: jellyfin
  template:
    spec:
      affinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist
      containers:
      - name: jellyfin
        resources:
          limits:
            gpu.intel.com/i915: 1000m
        volumeMounts:
        - mountPath: /data
          name: media
        - mountPath: /config
          name: config
      volumes:
      - name: media
        persistentVolumeClaim:
          claimName: media
      - name: config
        persistentVolumeClaim:
          claimName: jellyfin-config
