apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin
  namespace: saga
  labels:
    hilmargustafs.com/group: internal
spec:
  defaultBackend:
    service:
      name: jellyfin
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - jellyfin