apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: flux-system
spec:
  valuesFrom:
    - kind: Secret
      name: tailscale-oauth
  chart:
    spec:
      chart: tailscale-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tailscale
  driftDetection:
    mode: enabled
  interval: 24h0m0s
  releaseName: tailscale-operator
  targetNamespace: tailscale
