apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tei-model-cache
  namespace: embed
spec:
  storageClassName: longhorn-trusty
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
