apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyseerr
  labels:
    hilmargustafs.com/group: internal
spec:
  defaultBackend:
    service:
      name: jellyseerr
      port:
        name: http
  ingressClassName: tailscale
  tls:
    - hosts:
        - jellyseerr