apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-trusty
  resources:
    requests:
      storage: 1Gi