apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/arrs
- ../../configMaps/linuxserver
- namespace.yaml
- prowlarr-ingress.yaml
- prowlarr-config-pvc.yaml
- radarr-ingress.yaml
- radarr-config-pvc.yaml
- sonarr-ingress.yaml
- sonarr-config-pvc.yaml
- readarr-ingress.yaml
- readarr-config-pvc.yaml
- bazarr-ingress.yaml
- bazarr-config-pvc.yaml

namespace: arrs

patches:
- path: prowlarr-deployment-patch.yaml
- path: radarr-deployment-patch.yaml
- path: sonarr-deployment-patch.yaml
- path: readarr-deployment-patch.yaml
- path: bazarr-deployment-patch.yaml