---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  selector:
    matchLabels:
      app: radarr
  template:
    spec:
      containers:
      - name: radarr
        volumeMounts:
        - mountPath: /media
          name: media
        - mountPath: /config
          name: radarr-config
      volumes:
      - name: media
        nfs:
          path: /media/
          server: 10.240.1.43
      - name: radarr-config
        persistentVolumeClaim:
          claimName: radarr-config