---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: recyclarr
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: recyclarr
            volumeMounts:
            - mountPath: /media
              name: media
            - mountPath: /config
              name: recyclarr-config
          volumes:
          - name: media
            nfs:
              path: /media/
              server: 10.240.1.43
          - name: recyclarr-config
            persistentVolumeClaim:
              claimName: recyclarr-config
