apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: music-assistant-data
  namespace: smarthome
spec:
  storageClassName: longhorn-trusty
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce
