---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      chart: cert-manager
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
      version: 1.12.x
  interval: 1m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  driftDetection:
    mode: enabled
  values:
    installCRDs: true
