---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: intel-device-plugins-operator
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://intel.github.io/helm-charts/
