---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: intel-device-plugins
  namespace: flux-system
spec:
  chart:
    spec:
      chart: intel-device-plugins-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: intel-device-plugins-operator
        namespace: flux-system
      version: 0.30.0
  interval: 1m0s
  releaseName: intel-device-plugins
  targetNamespace: intel-device-plugins
  driftDetection:
    mode: enabled
