apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
  namespace: smarthome
spec:
  storageClassName: longhorn-trusty
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
