# yaml-language-server: $schema=https://json.schemastore.org/json-patch.json
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value:
    mountPath: /config
    name: config
- op: add
  path: /spec/template/spec/volumes/-
  value:
    name: config
    persistentVolumeClaim:
      claimName: transmission-config