---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/transmission
- ../../configMaps/linuxserver
- transmission-config-pvc.yaml

namespace: transmission

patches:
  - path: deployment-patches.yaml
    target:
      kind: Deployment
      name: transmission
