---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
  namespace: transmission
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-trusty
  resources:
    requests:
      storage: 100Mi