apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  interval: 10m0s
  path: ./apps/talos
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: infrastructure
    - name: secrets
  patches:
    - target:
        group: networking.k8s.io
        version: v1
        kind: Ingress
        labelSelector: hilmargustafs.com/group=internal
      patch: |-
        - op: add
          path: /metadata/annotations/tailscale.com~1tags
          value: "tag:k8s,tag:internal"