---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: flux-system
spec:
  install:
    createNamespace: true
  values:
    oauth:
      clientId: kVmrWqBys211CNTRL
      clientSecret: tskey-client-kVmrWqBys211CNTRL-ZZwymHcaHSabQDKjRVMjSa7eTJq5SUVc
  chart:
    spec:
      chart: tailscale-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: tailscale
  interval: 5m0s
  releaseName: tailscale-operator
  targetNamespace: tailscale
  postRenderers:
    - kustomize:
        patches:
          - patch: |-
              apiVersion: v1
              kind: Namespace
              metadata:
                name: tailscale
                labels:
                  pod-security.kubernetes.io/enforce: "privileged"
            target:
              apiVersion: v1
              kind: Namespace
              metadata:
                name: tailscale