---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: sops-secrets
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: ssh://git@github.com/lihram/sops-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sops-secrets
  namespace: flux-system
spec:
  targetNamespace: flux-system
  interval: 10m0s
  retryInterval: 2m
  timeout: 5m
  wait: true
  prune: true
  path: ./
  sourceRef:
    kind: GitRepository
    name: sops-secrets
  decryption:
    provider: sops
    secretRef:
      name: sops-age