apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sops
  namespace: flux-system
spec:
  targetNamespace: flux-system
  interval: 10m0s
  retryInterval: 2m
  timeout: 5m
  wait: true
  prune: true
  path: ./secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age