apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: saga
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  selector:
    app: jellyfin
  ports:
  - port: 80
    targetPort: 8096
