apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: flux-system
spec:
  chart:
    spec:
      chart: gatus
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minicloudlabs
  driftDetection:
    mode: enabled
  interval: 5m0s
  releaseName: gatus
  targetNamespace: minicloudlabs
