apiVersion: apps/v1
kind: Deployment
metadata:
  name: autobrr
  labels:
    app: autobrr
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: autobrr
  template:
    metadata:
      labels:
        app: autobrr
    spec:
      containers:
        - name: autobrr
          image: ghcr.io/autobrr/autobrr:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 7474
              protocol: TCP
              name: http
          env:
            - name: AUTOBRR__HOST
              value: "0.0.0.0"
          envFrom:
            - configMapRef:
                name: linuxserver-common
                optional: false
