apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- prowlarr-deployment.yaml
- prowlarr-service.yaml
- radarr-deployment.yaml
- radarr-service.yaml
- sonarr-deployment.yaml
- sonarr-service.yaml
- readarr-deployment.yaml
- readarr-service.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 200m
    