apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- prowlarr-deployment.yaml
- prowlarr-service.yaml
- radarr-deployment.yaml
- radarr-service.yaml
- sonarr-deployment.yaml
- sonarr-service.yaml
- readarr-deployment.yaml
- readarr-service.yaml
