apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- prowlarr-deployment.yaml
- prowlarr-service.yaml
- radarr-deployment.yaml
- radarr-service.yaml
- sonarr-deployment.yaml
- sonarr-service.yaml
- readarr-deployment.yaml
- readarr-service.yaml
- bazarr-deployment.yaml
- bazarr-service.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          limits:
            cpu: 200m
            memory: 300Mi
    