# yaml-language-server: $schema=...

apiVersion: batch/v1
kind: CronJob
metadata:
  name: recyclarr-radarr
  labels:
    app: recyclarr-sync
spec:
  schedule: "0 6 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: recyclarr
              image: ghcr.io/recyclarr/recyclarr:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: linuxserver-common
                    optional: false
              command: ["radarr"]
          restartPolicy: OnFailure
