apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-jellyfin
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    readOnly: false
    path: /Public/config/jellyfin
    server: 10.240.1.43
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-jellyfin
  namespace: saga
spec:
  volumeName: config-jellyfin
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi