# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.14.0/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tei
  namespace: embed
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: tei
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tei
    spec:
      containers:
        - name: tei
          image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.9
          imagePullPolicy: IfNotPresent
          args:
            - "--model-id"
            - "BAAI/bge-small-en-v1.5"
            - "--port"
            - "80"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - mountPath: /data
              name: model-cache
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: tei-model-cache
