apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage
  namespace: default
  tailscale.com/tags: "tag:k8s,tag:internal"
spec:
  defaultBackend:
    service:
      name: homepage
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - homepage
