apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitplay
  labels:
    app: bitplay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitplay-pod
  template:
    metadata:
      labels:
        app: bitplay-pod
    spec:
      containers:
        - name: bitplay
          image: ghcr.io/aculix/bitplay:main
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 3347
              protocol: TCP
              name: http
