---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitplay
  labels:
    app: bitplay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitplay
  template:
    metadata:
      labels:
        app: bitplay
    spec:
      containers:
        - name: bitplay
          image: ghcr.io/aculix/bitplay:1.0.0 # {"$imagepolicy": "flux-system:bitplay"}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
          env:
            - name: PROWLARR_URL
              value: "http://prowlarr.arrs.svc.cluster.local:9696"
            - name: PROWLARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: prowlarr-api-key
                  key: api-key
                  optional: true
          ports:
            - containerPort: 3347
              protocol: TCP
              name: http
