apiVersion: v1
kind: ConfigMap
metadata:
  name: transmission-config
  namespace: transmission
data:
  TRANSMISSION_DOWNLOAD_QUEUE_SIZE: "4"
  TRANSMISSION_RATIO_LIMIT: "2"
  TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
  TRANSMISSION_SPEED_LIMIT_DOWN: "10000"
  TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED: "true"
  TRANSMISSION_SPEED_LIMIT_UP: "1000"
  TRANSMISSION_SPEED_LIMIT_UP_ENABLED: "true"