apiVersion: ENC[AES256_GCM,data:nHo=,iv:5MaHUw06IPqpwzedSvwrjQczzDS4Z04Hp4SNNtpFZzU=,tag:myTKDJte/kWvS5u0i6tC3A==,type:str]
kind: ENC[AES256_GCM,data:SZyTwumX,iv:TwolfpMphYqbtAFRupbuiZTeaT9S1z3/mt7J7nE3gJI=,tag:R772KCucGjppCHejNh8T1g==,type:str]
metadata:
  name: ENC[AES256_GCM,data:pAmx4UGr+sR/XE/+uga6Yh9KkQnElA==,iv:ECH31cY4CrDkdv4kdsU+NPCPiN/ctJ4o5edQweUPoPU=,tag:Ytonkp8SCNuy82OknOptZA==,type:str]
  namespace: ENC[AES256_GCM,data:zQ/4/w==,iv:HYnSz06WdK9xqRF3+RhyYie1H7qwxXqQ71jrJDbzdyg=,tag:hQ5mrQmU7cMs6orA4LlLnQ==,type:str]
stringData:
  QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:AdJ6yVAfI3AlyWNF+tLP4iC2vGQrCIOWq3SWS4BOcrOPOAWS8OlRC+D6KjCPUGQ2rzr1tRC/nHoXw9ZMSi8bBA==,iv:aS12nShAJiF+2sJVG1WrCP7hCs/0KHSgxfNyZi/lCp4=,tag:TW7K7vPlywYK3wFEt6pfDA==,type:str]
  RADARR_API_KEY: ENC[AES256_GCM,data:Md2xmgWRhD9/+2bKa9MEO4WgRxjgYit61kIn653DwQs=,iv:2dcqoizcwUb2v1/DnK2fi3ymq+BSLUcmQxPoImTrSMw=,tag:j/odZwklIYRRProUGYEulg==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:ZYpH0Zfkqs3AOKgoAvwRE2xVB2N+M9+qX7HdabgQ/+s=,iv:/02V8d4wIejcc3daJboT/b6JYjXrUce0ZCfmTP3yx6E=,tag:KcQrggWw4K4GxR814wOO7Q==,type:str]
  LIDARR_API_KEY: ENC[AES256_GCM,data:BjYKT7Hrb+uRJfeu30hxybkR4cPbuXsJ8xLAYetE6k4=,iv:lF22hBw58+UXv+lOtLkxvw0Y1lL69EzZ1TxHSBIRyTk=,tag:tqel9+5ICaZTIP/oKFqpLA==,type:str]
sops:
  age:
    - recipient: age1m63ha7hp083mc3yf7pkax6y9zj7mg6u4dlqy9v2lzh7kdwtwtsxqz45xad
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOFlvTTZGNnNLMzdUSklB
        REgyVENkT2x5NHBJNHBKblRPcVpQcnhmZVdFCk12L1ZZMVZ6dlY0SzBWamVxVWZ6
        dS8xNTF2TEx3T2thV1ByUk13d2wvOWcKLS0tIHkwVEtNakVJemRJUDVFMGNRaG5s
        UDZrSUY3elNSa1BFanZFM3g4V0hBaEEKdFarq1pQVswhKwgBfDslCqi2m2bKsPwQ
        3u3jP/bynFIUiWbztFS1WAuYzhuXwc5eq+r7v0MchUBEHjTIg3dYTw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-21T08:36:40Z"
  mac: ENC[AES256_GCM,data:KZ0/Agp49nwY4PmWwOsVCA/i7whJ3ozfF+GFq2l3uS7EIY/Qspvs7xsgu5hAAcTJvmt2Bu2PdUdHBXgl6ck8ZWFe3MtcKqH6d1ZDY1jeA5iJj0TEQ/R3QNgHAoo/bo3dAnJtW/4RWgh1ILjObvoOyTt8ZnylLakcYNnsXLTjENw=,iv:xpr1HKrr+IBxma952gl37SGSX2EER4B+PFn17ELOGt8=,tag:uE/AoBdtS3GQ5gF+tw/zng==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
