apiVersion: v1
stringData:
  VPN_SERVICE_PROVIDER: ENC[AES256_GCM,data:fGgXm1TTowQU,iv:LV7TdUI3YXQJGWG8aWU14CafNzak3GCIxPS3GYjSFfo=,tag:Y7+4zcDzlsKkkN5rnZv6Gw==,type:str]
  SERVER_COUNTRIES: ENC[AES256_GCM,data:qhQ+TZxgbw==,iv:kWmzTwZ3tJu3l+zZqH70si7jkzE7bmFLT4gNPv0x0mg=,tag:I7YYkHtQvzrJBH4CK0pc4A==,type:str]
  OPENVPN_USER: ENC[AES256_GCM,data:MtsNn9JZK3c62FAHaAXSBjc1+Xp4OJFC,iv:m1vhGnOSQJE+OR7FjrgYuG6RJ+KI+pgMrsZfvoTtHhg=,tag:LZLxPoGabobQzOMflYma9w==,type:str]
  OPENVPN_PASSWORD: ENC[AES256_GCM,data:qQ753ySMbhnWEYoNAQ0YZF58uZi81GuE,iv:VNJHH+gx178GWn+L1rY9hXUUfHYRhnQzF3MoN597Ido=,tag:KvUOJLdxfzfsG8ztFJzbiA==,type:str]
kind: Secret
metadata:
  name: gluetun
  namespace: transmission
type: Opaque
sops:
  age:
    - recipient: age1m63ha7hp083mc3yf7pkax6y9zj7mg6u4dlqy9v2lzh7kdwtwtsxqz45xad
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKQlRraEJOZUdwVXRGU1Vz
        UWN0eU5rOGE1V1UrVWZmU01LanVYVEZ6MFYwCjgyZ05sWGR4YS9nTUIwVTA4WEtw
        WVlkRFl6TGhUOTdNeXdubnlVbU85VVUKLS0tIGlZU3h2OVMvNnlaOWVYQnMvTXh5
        S0hzcUhkMDdRNVFQUEgwbzRpOGxFdTQKKXZiewSZ/cm96XctnEW+5sIWwLafNmrC
        kJVFtB8TlMrmZBV5HSLBvf7FVclT2zg99uJK2D62v0cauvyBNC7nTA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-09-18T09:52:38Z"
  mac: ENC[AES256_GCM,data:UiZTVZENX+Mu5NHQlqghjzKpKQ6AI3P8YUL1QlyjkLrjL7IdoDM2s36SsvHGPgygV8OXLbeNa+KWJQAnZKX5wYOpPKlCJgQgjA5OBcIYDAoa+7CKL2iu3RdscXQuKyZXCGjqiTdlM2X93VKdU2he1pt13Ogsvlg8FNVB7xNhmuQ=,iv:B0VZDnhb9dEoE384hC06neCumpkr8xuzsH8Kf/kizrM=,tag:dPRp8KkH9lcWJOGHOVp5YQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
