apiVersion: v1
kind: Secret
metadata:
  name: tailscale-oauth
  namespace: flux-system
type: Opaque
data:
  values.yaml: ENC[AES256_GCM,data:2CN3euC4NO8VLpQS9bAGrwbu1zJ76GxBHm5Z+n5FQOJz8wnXEw+fYppDD9dMaArMtF33uuqDnRVaVuH19f6YzAs/Zd1hwIl/sxc/jCWBORQIh8XaXFlHjwFiPxKspIAjcExXtqua08x1ge9/n1WyjtbImzZFs+F1JqsZ7Ke4eQ5moadv8Ychf77BoX2iuxQJ/eZ+DKU9EWczXHq8EfY6iA==,iv:gKGQsM5ls/hKYE4KItyrwSMQRE6iL2aCIxupH/oWdwc=,tag:HFFpqravIKwAYQm89QsBSw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m63ha7hp083mc3yf7pkax6y9zj7mg6u4dlqy9v2lzh7kdwtwtsxqz45xad
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLN0gvV2sva0RGZ1luMGxV
        N2tiWHhuUFdSS0VsVFVyZFN3ejZ3RnZJUEJBCkxQUnB0azlUM3dRRzdxeFlzcHEw
        U2krQXdpU0Y3cTN5TG51Uy9xYU1qR28KLS0tIFA3ZFc2czIzV2tld3hRMTFqR1FK
        RmZqUkVacDRnZlNsbndRTnoxZ1RZenMKAPtP1vldDbZalK/aqMDlBlkv8vIHryAB
        3PAqsyjfnub83SxGeq1sAqo52JlZhsQM+0cImYVMPwGNfxlRpUxYCw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-22T16:15:28Z"
  mac: ENC[AES256_GCM,data:OvFl3oGchsCtDViLUUvRYAxpCLe0tv9kmGVdndZ2A9akQwee3IBZ1a/YJQgoZ/r3HiVfd7yp+4NdOqKdY+Kp5vweUq0tOajH6x33zIOe3QkYL8mPS1tGxAKU3dZYVgBQ6VnQ64unkjtkfpHSmM9rqeMnRoS3g0qJPxDuojvAl7Q=,iv:qmGKM/hqPBYxtrzKP/kf/9/yMV4zwMaR9hftYhcxJ1Q=,tag:EYNB/GJs/cOBxJKNioPr3g==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.2
