apiVersion: v1
kind: PersistentVolume
metadata:
  name: ntfy
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    lun: 1
    iqn: iqn.2004-04.com.qnap:ts-233:iscsi.homelab.7069f3
    targetPortal: 10.240.1.43
    fsType: ext4