apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-homebase
  namespace: flux-system
spec:
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    force: true
  chartRef:
    kind: HelmChart
    name: minecraft-java-server
  driftDetection:
    mode: enabled
  interval: 5m0s
  releaseName: minecraft
  targetNamespace: minecraft
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Service
            patch: |-
              - op: replace
                path: /spec/type
                value: LoadBalancer
              - op: add
                path: /spec/loadBalancerClass
                value: tailscale
  values:
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      type: "PAPER"
      pluginUrls:
        # Hangar URL: https://hangar.papermc.io/
        # Hangar shows all available PaperMC plugins that are compatible with this instance.
        - https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        - https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
        - https://github.com/JNNGL/VanillaMinimaps/releases/download/v1.0.0/vanillaminimaps-1.0.0.jar
        - https://hangarcdn.papermc.io/plugins/ViaVersion/ViaVersion/versions/5.1.1/PAPER/ViaVersion-5.1.1.jar
      motd: ""
      pvp: false
      ops: lihram
      serviceType: LoadBalancer
      extraPorts:
        - name: geyser
          containerPort: 19132
          protocol: UDP
          service:
            enabled: true
            type: LoadBalancer
            port: 19132
            loadBalancerClass: tailscale
    persistence:
      storageClass: longhorn-trusty
      dataDir:
        enabled: true
    rcon:
      enabled: true
      withGeneratedPassword: true
    mcbackup:
      enabled: true
      persistence:
        storageClass: longhorn-trusty
        backupDir:
          enabled: true
