apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-homebase
  namespace: flux-system
spec:
  install:
    remediation:
      retries: 3
  chartRef:
    kind: HelmChart
    name: minecraft-java-server
  driftDetection:
    mode: enabled
  interval: 5m0s
  releaseName: minecraft
  targetNamespace: minecraft
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Service
              namespace: minecraft
            patch: |-
              - op: replace
                path: /spec/type
                value: LoadBalancer
              - op: add
                path: /spec/loadBalancerClass
                value: tailscale
  values:
    minecraftServer:
      eula: "TRUE"
      version: "LATEST"
      type: "PAPER"
      pluginUrls:
        - https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        - https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
      motd: ""
      pvp: false
      serviceType: LoadBalancer
      extraPorts:
        - name: geyser
          containerPort: 19132
          protocol: TCP
          service:
            enabled: true
            type: LoadBalancer
            port: 19132
            loadBalancerClass: tailscale
    persistence:
      storageClassName: longhorn-trusty
      dataDir:
        enabled: true