apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/minecraft
- helmrelease-homebase.yaml

patches:
  - target:
      version: v1
      kind: Service
      namespace: minecraft
    patch: |-
      - op: replace
        path: /spec/loadBalancerClass
        value: tailscale