---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-config
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-trusty
  resources:
    requests:
      storage: 100Mi