---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    name: jellyfin
spec:
  selector:
    matchLabels:
      task: jellyfin
  template:
    metadata:
      labels:
        task: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: lscr.io/linuxserver/jellyfin
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8096
              protocol: TCP
            - containerPort: 7359
              protocol: UDP
            - containerPort: 1900
              protocol: UDP
          env:
            - name: PUID
              valueFrom:
                configMapKeyRef:
                  name: linuxserver-common
                  key: PUID
            - name: PGID
              valueFrom:
                configMapKeyRef:
                  name: linuxserver-common
                  key: PGID
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: linuxserver-common
                  key: TZ
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: app
spec:
  ports:
    - name: http
      port: 8096
    - name: client-disc
      port: 7359
    - name: service-disc
      port: 1900
  selector:
    task: jellyfin