# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.14.0/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: ghcr.io/linuxserver/jellyfin:10.10.6
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 5Gi
          ports:
            - containerPort: 8096
              protocol: TCP
              name: http
            - containerPort: 7359
              protocol: UDP
            - containerPort: 1900
              protocol: UDP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 30
          envFrom:
            - configMapRef:
                name: linuxserver-common
                optional: false
