---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: ghcr.io/linuxserver/jellyfin
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
          ports:
            - containerPort: 8096
              protocol: TCP
            - containerPort: 7359
              protocol: UDP
            - containerPort: 1900
              protocol: UDP
          env:
            - name: PUID
              valueFrom:
                configMapKeyRef:
                  name: linuxserver-common
                  key: PUID
            - name: PGID
              valueFrom:
                configMapKeyRef:
                  name: linuxserver-common
                  key: PGID
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: linuxserver-common
                  key: TZ
