- Movies & TV:
    - jellyfin:
        href: https://jellyfin.tyrannosaurus-turtle.ts.net
        description: "Stream media"
        icon: jellyfin.png
    - sonarr:
        href: https://sonarr.tyrannosaurus-turtle.ts.net
        description: "Manage series"
        icon: sonarr.png
    - radarr:
        href: https://radarr.tyrannosaurus-turtle.ts.net
        description: "Manage movies"
        icon: radarr.png
    - bazarr:
        href: https://bazarr.tyrannosaurus-turtle.ts.net
        description: "Manage subtitles"
        icon: bazarr.png
- Books:
    - readarr:
        href: https://readarr.tyrannosaurus-turtle.ts.net
        description: "Manage books"
        icon: readarr.png
- Shared:
    - prowlarr:
        href: https://prowlarr.tyrannosaurus-turtle.ts.net
        description: "Manage indexers"
        icon: prowlarr.png
    - ntfy:
        href: https://ntfy.tyrannosaurus-turtle.ts.net
        description: "Notifications"
        icon: ntfy.png
    - transmission:
        href: https://transmission.tyrannosaurus-turtle.ts.net
        description: "Downloads"
        icon: transmission.png
        widget:
            type: transmission
            url: transmission.transmission.svc.cluster.local
            username: ""
            password: ""
