apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bitplay
  namespace: streaming
  labels:
    hilmargustafs.com/group: internal
spec:
  defaultBackend:
    service:
      name: bitplay
      port:
        number: 80
  ingressClassName: tailscale
  tls:
    - hosts:
        - jellyfin
