apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft
  namespace: flux-system
spec:
  chart:
    spec:
      chart: minecraft
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: itzg
  driftDetection:
    mode: enabled
  interval: 5m0s
  releaseName: minecraft
  targetNamespace: minecraft
