apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  name: minecraft-java-server
  namespace: flux-system
spec:
  interval: 5m0s
  chart: minecraft
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: itzg